### ISSUE TITLE
pre-built download?

### ISSUE THREAD

**Issue by ghost** [bnoordhuis/node-buffertools#21]
can you offer a pre-built download for buffertools, so that those of us on windows can just download and use it?
i actually just wanna use 'https://github.com/eleith/emailjs' but it requires this module

edit: it seems that 'emailjs' only requires the 'buffertools.concat' function, so if its not possible to provide a pre-built download, can you please tell me what's the difference between 'buffertools.concat' and 'Array.prototype.concat'?

**Comment by bakesteve** [comment]
now in 2015 - is there any way to get movement on this?
I'm trying to use flowdock on a build server, and its failing due to the age old node-gyp issues. hopefully one day that will get resolved.. but in the meantime is there any reason not to include a /dist folder and avoid the runtime python dependency (dev dependency - fine, its just when you want to use npm as a way to install a package + deps)

**Comment by bnoordhuis** [comment]
I don't use Windows myself but if anyone is willing to do the work on that, then sure.

**Comment by bakesteve** [comment]
sure, any preference on the approach?
I'd assume [node-pre-gyp](https://github.com/mapbox/node-pre-gyp), and travis / appveyor to publish the prebuilt dist?
[here is a detailed guide on that](http://cylonjs.com/blog/2014/11/19/creating-multiplatform-precompiled-binaries-for-node-modules/)

**Comment by Matthew-Davey** [comment]
It would be helpful to state in the readme that this package is not compatible with Windows.

**Comment by bnoordhuis** [comment]
@Matthew-Davey It's compatible, but you need a C++ compiler to build it.  Most platforms install one by default, Windows doesn't.  It's not a requirement unique to node-buffertools, all native node add-ons have the same dependency (although some publish pre-compiled binaries.)

**Comment by Matthew-Davey** [comment]
Hi there, thanks for the help. Here is the error I get when I `npm install buffertools`. Please note that I do use some other packages with native add-ons, eg Nokogiri.

```
$>npm install buffertools

> buffertools@2.1.4 install C:\...\node_modules\buffertools
> node-gyp rebuild


C:\...\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\...\AppData\Roaming\nvm\v6.3.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  buffertools.cc
c:\...\node_modules\buffertools\BoyerMoore.h(35): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vc xproj]
c:\...\node_modules\buffertools\BoyerMoore.h(57): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vc xproj]
c:\...\node_modules\buffertools\BoyerMoore.h(61): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\...\node_modules\buffertools\build\buf fertools.vcxproj]
c:\...\node_modules\buffertools\BoyerMoore.h(61): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data [C:\...\node_modules\buffertools\bui ld\buffertools.vcxproj]
c:\...\node_modules\buffertools\BoyerMoore.h(62): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\...\node_modules\buffertools\build\buf fertools.vcxproj]
c:\...\node_modules\buffertools\BoyerMoore.h(62): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data [C:\...\node_modules\buffertools\bui ld\buffertools.vcxproj]
c:\...\node_modules\buffertools\BoyerMoore.h(110): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.v cxproj]
..\buffertools.cc(219): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(219): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(220): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(220): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(332): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(334): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(340): warning C4244: 'argument': conversion from 'const ptrdiff_t' to 'int32_t', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(419): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\...\node_modules\buffertools\build\buffertools.vcxproj]
  win_delay_load_hook.c
C:\...\Roaming\nvm\v6.3.1\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\...\node_modules\buffertools\build\buffertools.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\...\AppData\Roaming\nvm\v6.3.1\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\...\\AppData\\Roaming\\nvm\\v6.3.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\...\node_modules\buffertools
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\...\package.json'
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "buffertools"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! buffertools@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@2.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buffertools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\...\npm-debug.log
```

**Comment by bnoordhuis** [comment]
@Matthew-Davey Upgrade to node-gyp@3.4.0, that will fix the __pfnDliNotifyHook2 error.

**Comment by igorpupkinable** [comment]
Compilation issue for Windows should be solved by installing [Visual C++ 2015 Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools).

Please see [comment from Microsoft](https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245) team from more details.
Download [latest Visual C++ 2015 Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) for Windows.
