### ISSUE TITLE
Can't install buffertools on iojs

### ISSUE THREAD

**Issue by Spy-Seth** [bnoordhuis/node-buffertools#67]
I'm trying to use a package who depend on buffertools. But the install of buffertools fails during the compilation phase: 

```
$ npm install
npm http request GET https://registry.npmjs.org/buffertools
npm http 304 https://registry.npmjs.org/buffertools

> buffertools@2.1.3 install /Users/spy-seth/workspace/web.client.vlr/node_modules/buffertools
> node-gyp rebuild

gyp http GET https://nodejs.org/dist/v2.4.0/node-v2.4.0.tar.gz
gyp http 404 https://nodejs.org/dist/v2.4.0/node-v2.4.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v2.4.0/node-v2.4.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/spy-seth/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/spy-seth/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Users/spy-seth/.nvm/versions/io.js/v2.4.0/bin/iojs" "/Users/spy-seth/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/spy-seth/workspace/web.client.vlr/node_modules/buffertools
gyp ERR! node -v v2.4.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN install:buffertools Couldn't install optional dependency: buffertools@2.1.3 install: `node-gyp rebuild`
npm WARN install:buffertools Exit status 1

> bufferutil@1.1.0 install /Users/spy-seth/workspace/web.client.vlr/node_modules/bufferutil
> node-gyp rebuild

gyp http GET https://nodejs.org/dist/v2.4.0/node-v2.4.0.tar.gz
gyp http 404 https://nodejs.org/dist/v2.4.0/node-v2.4.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v2.4.0/node-v2.4.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/spy-seth/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/spy-seth/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Users/spy-seth/.nvm/versions/io.js/v2.4.0/bin/iojs" "/Users/spy-seth/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/spy-seth/workspace/web.client.vlr/node_modules/bufferutil
gyp ERR! node -v v2.4.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/spy-seth/.nvm/versions/io.js/v2.4.0/bin/iojs" "/Users/spy-seth/.nvm/versions/io.js/v2.4.0/bin/npm" "install"
npm ERR! node v2.4.0
npm ERR! npm  v3.2.0
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/spy-seth/workspace/web.client.vlr/npm-debug.log
```

I've try with iojs 2.4.0 and iojs 3.0.0.

I do not understands why it try to download the node archive :/

**Comment by bnoordhuis** [comment]
This error:

> gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v2.4.0/node-v2.4.0.tar.gz

Means you're using the wrong node-gyp version, i.e., the one that ships with node.js, not io.js.

If you fix that, it should work with v2.x and v3.x; I took care of v3.x compatibility in 1912a92.  Good luck!

**Comment by Spy-Seth** [comment]
You can I force to last version `node-gyp`?

**Comment by bnoordhuis** [comment]
I think your question is how to pick the right node-gyp?  I speculate you have both node.js and io.js installed, or you upgraded the npm that came with io.js.  It contains a few patches that you'll lose when you upgrade npm manually.

**Comment by Spy-Seth** [comment]
Yes I upgrade to the NPM 3.x beta branch on iojs. So I suppose this is an issue for the NPM team.
