### ISSUE TITLE
npm install - build error

### ISSUE THREAD

**Issue by Anup-Allamsetty** [bnoordhuis/node-buffertools#77]
Like #61, for me build is failing at installation of buffertools 
```
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated sockjs-client-node@0.1.1: deprecated in favor of the official sockjs-client
npm WARN prefer global marked@0.3.2 should be installed with -g

> contextify@0.1.15 install /home/reznord/Workspace/docker-exec-websocket-server/node_modules/contextify
> node-gyp rebuild

make: Entering directory '/home/reznord/Workspace/docker-exec-websocket-server/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/obj.target/contextify.node
  COPY Release/contextify.node
make: Leaving directory '/home/reznord/Workspace/docker-exec-websocket-server/node_modules/contextify/build'

> bufferutil@1.2.1 install /home/reznord/Workspace/docker-exec-websocket-server/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/reznord/Workspace/docker-exec-websocket-server/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/reznord/Workspace/docker-exec-websocket-server/node_modules/bufferutil/build'

> buffertools@2.1.2 install /home/reznord/Workspace/docker-exec-websocket-server/node_modules/taskcluster-base/node_modules/buffertools
> node-gyp rebuild

make: Entering directory '/home/reznord/Workspace/docker-exec-websocket-server/node_modules/taskcluster-base/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
../buffertools.cc: In function ‘v8::Local<v8::Value> {anonymous}::decodeHex(const uint8_t*, size_t, const v8::FunctionCallbackInfo<v8::Value>&, uint32_t)’:
../buffertools.cc:42:22: error: conversion from ‘v8::MaybeLocal<v8::Object>’ to non-scalar type ‘v8::Local<v8::Object>’ requested
     node::Buffer::New(args.GetIsolate(), size)
                      ^
../buffertools.cc:367:26: note: in expansion of macro ‘UNI_BUFFER_NEW’
   Local<Object> buffer = UNI_BUFFER_NEW(size / 2);
                          ^
../buffertools.cc: In function ‘void {anonymous}::Concat(const v8::FunctionCallbackInfo<v8::Value>&)’:
../buffertools.cc:42:22: error: conversion from ‘v8::MaybeLocal<v8::Object>’ to non-scalar type ‘v8::Local<v8::Object>’ requested
     node::Buffer::New(args.GetIsolate(), size)
                      ^
../buffertools.cc:459:26: note: in expansion of macro ‘UNI_BUFFER_NEW’
   Local<Object> buffer = UNI_BUFFER_NEW(size);
                          ^
buffertools.target.mk:88: recipe for target 'Release/obj.target/buffertools/buffertools.o' failed
make: *** [Release/obj.target/buffertools/buffertools.o] Error 1
make: Leaving directory '/home/reznord/Workspace/docker-exec-websocket-server/node_modules/taskcluster-base/node_modules/buffertools/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/reznord/.nvm/v5.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-34-generic
gyp ERR! command "/home/reznord/.nvm/v5.9.0/bin/node" "/home/reznord/.nvm/v5.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/reznord/Workspace/docker-exec-websocket-server/node_modules/taskcluster-base/node_modules/buffertools
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN docker-exec-websocket-server@1.1.0 No license field.
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/home/reznord/.nvm/v5.9.0/bin/node" "/home/reznord/.nvm/v5.9.0/bin/npm" "install"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! buffertools@2.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@2.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buffertools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/reznord/Workspace/docker-exec-websocket-server/npm-debug.log
```

I tried the solution which you provided in #61 , still getting the same error. 

Thanks for the help.

**Comment by bnoordhuis** [comment]
Upgrade to v2.1.3, it contains the fix for that build error.  v2.1.2 is over two years old, FWIW.
