### ISSUE TITLE
'node-gyp rebuild' fails

### ISSUE THREAD

**Issue by peterdalydickson** [bnoordhuis/node-buffertools#78]
I just added the dependency `"hubot-flowdock": ">= 0.0.1"` to hubot's package.json.

Attempts to restart hubot now return...
```
/opt/jarvis$ bin/hubot -n jarvis

> buffertools@2.1.4 install /opt/jarvis/node_modules/buffertools
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:63:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:72:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:81:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/jarvis/node_modules/buffertools
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! buffertools@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@2.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buffertools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/jarvis/npm-debug.log
```
Is this a problem with buffertools, or with the flowdock adaptor?

I've attached npm-debug.log in case it helps.

cheers

Pete
[npm-debug.zip](https://github.com/bnoordhuis/node-buffertools/files/274211/npm-debug.zip)

**Comment by bnoordhuis** [comment]
> gyp ERR! stack Error: not found: make

You need to have make installed - and a C++ compiler and a linker too, for that matter.  If you're running Debian or Ubuntu, try `apt-get install build-essential`.

I'll close, not an issue with node-buffertools itself, any native module requires a compiler toolchain.

**Comment by peterdalydickson** [comment]
Doh! 

Forgot to add to new server. 

Should have read error message more closely! 

Thanks for your help. 

cheers 

P. 

--- 
Peter Daly-Dickson
