### ISSUE TITLE
The system cannot find message text for message number 0x%1 in the message file for %2 while require('buffertools') 

### ISSUE THREAD

**Issue by OgNellis** [bnoordhuis/node-buffertools#80]
Window7 x86
Node 5.10.1
I try to build buffertools such way:
```
node-gyp configure
node-gyp build -d
```

Then I got the error while requiring buffertools (`require('buffertools');`):
```
The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\D:\work\terminal_second\build\Wjbets-v0.1.03\node_modules\buffertools\build\Debug\buffertools.node"
```

**Comment by bnoordhuis** [comment]
Can you delete your node_modules directory and reinstall buffertools without `-d`?

**Comment by OgNellis** [comment]
Yes, I have tried to delete the node_modules and to reinstall buffertools but nothing changed.

**Comment by bnoordhuis** [comment]
Can you post the exact error message?  Does it still say Debug in the file path?

The error itself suggests buffertools has been compiled wrongly, e.g., for the wrong architecture.

**Comment by OgNellis** [comment]
```
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\D:\work\terminal_second\build\Wjbets-v0.1.03\node_modules\buffertools\build\Release\buffertools.node
at Error (native)
at Object.Module._extensions..node (module.js:476:18)
at Module.load (module.js:375:32)
at Function.Module._load (module.js:332:12)
at Module.require (module.js:385:17)
at require (internal/module.js:16:19)
at self.require (<anonymous>:11:26)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
```

When I compile information shows that it is compiled for x32

**Comment by bnoordhuis** [comment]
Am I right to assume that `node -p process.arch` says 'x64'?  If yes, what happens when you pass `--arch=x64` to node-gyp?

**Comment by OgNellis** [comment]
![image](https://cloud.githubusercontent.com/assets/2085343/16222897/601bc38a-37bc-11e6-86b5-aeafca599440.png)

**Comment by bnoordhuis** [comment]
Okay, then I'm afraid I don't know what the issue is.

**Comment by MrfksIv** [comment]
have anyone found I a solution to this? I get the same error when in my attempt to use electron with emberJS and zerorpc to communicate with python.
