### ISSUE TITLE
Just automatically upgraded to 2.1.5 and binaries were not built

### ISSUE THREAD

**Issue by alexw10** [bnoordhuis/node-buffertools#89]
Our project got automatically upgraded which took in the new buffertools release and we saw this error: 

```
Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alex.winter/projects/vdl-angular/node_modules/buffertools/buffertools.js:27:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

with 2.1.4 it looks like node gyp gets executed with this but this new version doesn't not run node gyp.

**Comment by bnoordhuis** [comment]
See https://github.com/npm/npm/issues/16243, I published v2.1.6 just now as a workaround.
