### ISSUE TITLE
Load error on Windows 10

### ISSUE THREAD

**Issue by rytrose** [bnoordhuis/node-buffertools#90]
Windows 10, Node v6.11.2, Electron v1.7.5
```
App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\rytro\ORG\app\node_modules\buffertools\build\Release\buffertools.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\rytro\ORG\app\node_modules\buffertools\buffertools.js:24:20)
    at Object.<anonymous> (C:\Users\rytro\ORG\app\node_modules\buffertools\buffertools.js:123:3)
```
I've tried most [methods of building](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) as I can find (with electron-rebuild successfully rebuilding), and I'm nearly positive my build tools are correct (I used [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) and my PATH seems alright) and can't seem to find why buffertools.node keeps crashing on the require.

**Comment by bnoordhuis** [comment]
Does another native module like heapdump work?

**Comment by rytrose** [comment]
I'm not sure why, but when I thought to use node-gyp directly to build to target my Electron version, it finally worked. I thought electron-rebuild was supposed to handle that, but it's working now. Sorry for the red herring!
